#!/bin/bash

green=`echo -en "\e[32m"`
normal=`echo -en "\e[0m"`
orange=`echo -en "\e[33m"`

#Create key
ssh-keygen -b 4096

read -e -i "master" -p "${green}Please enter username on server: $normal" username
echo $username

read -e -i "192.168.1.3" -p "${green}Please enter servername: $normal" servername
echo $servername

#copy key to server
ssh-copy-id $username@$servername

echo "${orange}Now u can continue with the ServerScript $normal"
